### ISSUE TITLE
Only add explanatory comment once per patchset

### ISSUE THREAD

**Issue by legoktm** [valhallasw/gerrit-patch-uploader#19]
When a patch is uploaded, a comment is added to it like: "This commit was uploaded using the Gerrit Patch Uploader [1]...."

This gets annoying when someone is just updating their patch (ex: https://gerrit.wikimedia.org/r/#/c/123128/).

Lets just add it once per patchset.

**Comment by valhallasw** [comment]
https://phabricator.wikimedia.org/T86350?workflow=create
